Repository slipstream/SlipStreamServer, pull requests merged in 2018-12, with the labels that each got.

#1729 Attempt to delete the underlying bucket whenever we delete a S3 object
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
Labels: S40 Ready to validate

#1730 module component support mounts and ports is now an array
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module_component.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_component_test.cljc
Labels: S40 Ready to validate

#1733 fix bad format specification
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
Labels: P22 GNSS, S40 Ready to validate, T5 Bug

#1734 fix format args
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
Labels: P22 GNSS, S40 Ready to validate, T5 Bug

#1731 Collect size checksum information for S3 objects
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object/utils_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_generic_test.cljc
Labels: S40 Ready to validate

#1735 Issue #1633 add public external objects
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_public.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_template_public.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_public.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_public.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object/utils_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_public_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_public_test.cljc
Labels: S40 Ready to validate

#1739 add templateMutable attribute to session template
  cimi/src/com/sixsq/slipstream/ssclj/resources/cloud_entry_point.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/cloud_entry_point.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_attribute.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/ui_hints.cljc
  cimi/src/com/sixsq/slipstream/ssclj/util/metadata.clj
  cimi/src/com/sixsq/slipstream/ssclj/util/spec.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/cloud_entry_point_lifecycle_test.clj
Labels: S40 Ready to validate

#1744 save dataset information
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/deployment_test.cljc
Labels: P22 GNSS, S40 Ready to validate, T2 Task

#1741 make class optional
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/evidence_record.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/evidence_record_test.cljc
Labels: S40 Ready to validate
