Repository slipstream/SlipStreamServer, pull requests merged in 2018-05, with the labels that each got.

#1500 explicit resource initialization
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/callback.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/connector.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/email.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/event.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_generic.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/metering.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/quota.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_attribute.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_attribute_namespace.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_benchmark.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_offer.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/virtual_machine.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/virtual_machine_mapping.clj
  cimi-test-jar/src/com/sixsq/slipstream/ssclj/resources/lifecycle_test_utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/cloud_entry_point.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/std_crud.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_slipstream.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_ssh_public_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_cyclone.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_params.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_params_exec.clj
  cimi/test/com/sixsq/slipstream/ssclj/util/es_mapping_test.cljc
  db-binding/project.clj
  db-binding/resources/com/sixsq/slipstream/db/es/mapping-not-analyzed.json
  db-binding/src/com/sixsq/slipstream/db/atom/binding.clj
  db-binding/src/com/sixsq/slipstream/db/es/binding.clj
  db-binding/src/com/sixsq/slipstream/db/es/common/es_mapping.cljc
  db-binding/src/com/sixsq/slipstream/db/es/common/utils.clj
  db-binding/src/com/sixsq/slipstream/db/es/utils.clj
  db-binding/src/com/sixsq/slipstream/db/es_rest/binding.clj
  db-binding/test/com/sixsq/slipstream/db/binding_lifecycle.clj
  db-binding/test/com/sixsq/slipstream/db/binding_queries.clj
  db-binding/test/com/sixsq/slipstream/db/es/binding_test.clj
  db-binding/test/com/sixsq/slipstream/db/es/common/es_mapping_test.cljc
  db-binding/test/com/sixsq/slipstream/db/es_rest/binding_test.clj
  db-binding/test/com/sixsq/slipstream/db/es_rest/test_utils.clj
  db-serializers/project.clj
  db-serializers/src/com/sixsq/slipstream/db/serializers/utils.clj
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1505 change to iso8601 expiry dates for session
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_cyclone.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session.cljc
  token/clj/src/com/sixsq/slipstream/auth/cookies.clj
  token/clj/src/com/sixsq/slipstream/auth/token_checker.clj
  token/clj/src/com/sixsq/slipstream/auth/utils/certs.clj
  token/clj/src/com/sixsq/slipstream/auth/utils/sign.clj
  token/clj/src/com/sixsq/slipstream/auth/utils/timestamp.clj
  token/clj/test/com/sixsq/slipstream/auth/utils/timestamp_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1509 do not use configuration to set version number
  jar-persistence/pom.xml
  jar-persistence/src/main/java/com/sixsq/slipstream/configuration/Configuration.java
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1510 initial db from ss-config
  cimi-tools/src/com/sixsq/slipstream/tools/cli/ssconfig.clj
  cimi-tools/src/com/sixsq/slipstream/tools/cli/ssconfigdump.clj
Labels: P45 MF2C, S10 Working, T5 Bug

#1511 fix session initialization and quota schema
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/quota.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_cyclone.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_oidc.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_internal_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1513 initialize db binding for java server
  db-serializers/src/com/sixsq/slipstream/db/serializers/utils.clj
  jar-persistence/src/main/java/com/sixsq/slipstream/es/CljElasticsearchHelper.java
  jar-service/src/main/java/com/sixsq/slipstream/application/RootApplication.java
  rpm/src/main/scripts/etc-default-slipstream
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1514 allow upload to be called in uploading state
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1516 Use new ES6 indices and type for virtual machine and metering
  metering-rpm/src/scripts/metering
  metering/src/sixsq/slipstream/metering/metering.clj
  metering/test/sixsq/slipstream/metering/metering_test.clj
Labels: S40 Ready to validate

#1517 migration
  cimi-migration/pom.xml
  cimi-migration/project.clj
  cimi-migration/resources/log4j.properties
  cimi-migration/src/assembly/src.xml
  cimi-migration/src/com/sixsq/slipstream/tools/cli/dbcopy.clj
  cimi-migration/src/com/sixsq/slipstream/tools/cli/dbinit.clj
  cimi-migration/src/com/sixsq/slipstream/tools/cli/utils.clj
  pom.xml
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1519 Fix command line parsing
  cimi-tools/src/com/sixsq/slipstream/tools/cli/ssconfig.clj
  cimi-tools/src/com/sixsq/slipstream/tools/cli/ssconfigdump.clj
  cimi-tools/src/com/sixsq/slipstream/tools/cli/ssconfigmigrate.clj
  cimi-tools/test/com/sixsq/slipstream/tools/cli/utils_test.clj
Labels: S40 Ready to validate

#1520 set/subset? function requires sets arguments
  cimi-tools/src/com/sixsq/slipstream/tools/cli/ssconfig.clj
  cimi-tools/test/com/sixsq/slipstream/tools/cli/utils_test.clj
Labels: S40 Ready to validate

#1523 Do not automatically create user for unmatched user in database
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_cyclone.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_oidc.clj
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_oidc_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1525 clean up api key/secret even on aborted runs
  jar-connector/src/main/java/com/sixsq/slipstream/connector/CliConnectorBase.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/CliConnectorBaseTest.java
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1527 Use test data from ES6 index
  metering/test-resources/virtual-machines.json
  metering/test/sixsq/slipstream/metering/metering_test.clj
Labels: S40 Ready to validate

#1528 remove old migration scripts
  cimi-migration/pom.xml
  cimi-migration/project.clj
  cimi-migration/resources/log4j.properties
  cimi-migration/src/assembly/src.xml
  cimi-migration/src/com/sixsq/slipstream/tools/cli/dbcopy.clj
  cimi-migration/src/com/sixsq/slipstream/tools/cli/dbinit.clj
  cimi-migration/src/com/sixsq/slipstream/tools/cli/utils.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1531 move callbacks; update execute signature
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/callback_email_validation.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/callback_user_email_validation.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/connector.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/connector_template.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_template.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/quota.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/std_crud.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/callback.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_params_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/callback/utils_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/callback_example.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/callback_example_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/callback_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/callback_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1533 add add-if-absent utility for initialization
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/std_crud.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_slipstream.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/configuration_slipstream_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1534 remove vestiges of having slipstream version in configuration
  cimi/resources/com/sixsq/slipstream/version.txt
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_slipstream.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1536 rationalize user and user template schemas
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/user_self_registration.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/user_template_self_registration.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration_test.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_direct.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_direct.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_direct.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1537 Feature/user validation email ta c
  cimi-deployment/components/traefik/cert/do-not-remove
  cimi-deployment/components/traefik/cert/server.crt
  cimi-deployment/docker-compose.yml
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/email/utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/email_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
  cimi-rpm/pom.xml
  cimi/resources/com/sixsq/slipstream/ssclj/resources/configuration-slipstream-desc.edn
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_slipstream.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_slipstream.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_slipstream.cljc
  db-serializers/src/com/sixsq/slipstream/db/serializers/service_config_impl.clj
  db-serializers/test/com/sixsq/slipstream/db/serializers/service_config_test.clj
Labels: S40 Ready to validate

#1538 remove test dependencies from cimi artifact; remove spec.gen.alpha
  cimi-resources/project.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/connector_template.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/event.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_attribute.cljc
  cimi/project.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/util/spec.cljc
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1539 move resources that are used by mf2c to cimi submodule
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_email_validation.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_user_email_validation.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/email.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/email_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/email_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1540 move self-registration resources from cimi-resources to cimi for mf2c
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_self_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_self_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user/utils_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task
