Repository slipstream/SlipStreamServer, pull requests merged in 2018-11, with the labels that each got.

#1690 automatic metadata registration
  cimi/src/com/sixsq/slipstream/ssclj/resources/cloud_entry_point.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template_ssh_key_pair.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template_ssh_public_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/resource_metadata.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_mitreid_token.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/cloud_entry_point.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_ssh_key_pair.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/email.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/ui_hints.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_identifier.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_github.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_mitreid.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_oidc.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_github_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_identifier.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_oidc_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_direct.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_github_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_self_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/util/metadata.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/cloud_entry_point_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/credential_template_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/email_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/resource_metadata_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_api_key_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_internal_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_mitreid_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_mitreid_token_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_oidc_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/email_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_github_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_mitreid_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_oidc_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_identifier_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_direct_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_mitreid_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_oidc_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_self_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/util/metadata_test_utils.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1694 metadata fixes
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template_ssh_key_pair.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template_ssh_public_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/resource_metadata.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_mitreid_token.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_direct.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_self_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/util/metadata.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/resource_metadata_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/util/metadata_test_utils.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1698 add fields to module for data format/protocol matching
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_test.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
Labels: P22 GNSS, S40 Ready to validate, T2 Task

#1700 add data attributes to deployment
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_template.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/job.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment/test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/deployment_test.cljc
Labels: P22 GNSS, S40 Ready to validate

#1702 rename attributes
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/deployment_test.cljc
Labels: P22 GNSS, S40 Ready to validate

#1705 expand the range of values for :connector/href in service offer
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_offer.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_offer_test.cljc
Labels: P22 GNSS, S40 Ready to validate, T2 Task

#1709 move metadata utils to common test area
  cimi-test-jar/src/com/sixsq/slipstream/ssclj/util/metadata_test_utils.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1712 generate events for cimi deployment
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_parameter.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/event.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/event/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/event.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_offer.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_parameter_lifecycle_test.clj
Labels: S40 Ready to validate

#1713 update module migration
  rpm/src/main/migrations/022_migrate_module_to_cimi.py
Labels: P22 GNSS, S40 Ready to validate

#1716 update logo attribute
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment/test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_test.cljc
  rpm/src/main/migrations/022_migrate_module_to_cimi.py
Labels: P22 GNSS, S40 Ready to validate, T2 Task

#1722 migrate docs
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/event.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/metering.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/quota.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_attribute.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_attribute_namespace.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_benchmark.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_offer.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/virtual_machine.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/cloud_entry_point.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_ssh_public_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_identifier.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_params.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_params_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1725 Task/metadata gen
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/acl.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/cloud_entry_point.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_ssh_key_pair.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_ssh_public_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/email.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_action.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_attribute.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_capability.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_internal.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_mitreid_token.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/test_spec.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/ui_hints.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_identifier.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration.cljc
  cimi/src/com/sixsq/slipstream/ssclj/util/spec.cljc
  cimi/test/com/sixsq/slipstream/ssclj/util/es_mapping_test.cljc
  db-binding/src/com/sixsq/slipstream/db/es/common/es_mapping.cljc
  db-binding/test/com/sixsq/slipstream/db/es/common/es_mapping_test.cljc
Labels: S40 Ready to validate

#1727 initial state provisioning and exploitable events
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_parameter.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_parameter_lifecycle_test.clj
Labels: S40 Ready to validate

#1717 Issue #1632 external object issues
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_test.clj
Labels: S40 Ready to validate

#1728 move ports to module
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module_component.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment/test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_component_test.cljc
Labels: S40 Ready to validate
