Repository slipstream/SlipStreamServer, pull requests merged in 2018-04, with the labels that each got.

#1471 allow user to view connector collection
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/connector.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/connector_lifecycle_test.clj
Labels: P66 EU-SEC, S40 Ready to validate, T2 Task

#1475 set es id to be consistent with cimi resource id
  metering/src/sixsq/slipstream/metering/metering.clj
  metering/test/sixsq/slipstream/metering/metering_live_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1476 Allow connector subtype to redefine identifier
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/connector.clj
Labels: S40 Ready to validate, T3 Enhancement

#1477 specs with ns-qualified keywords
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/callback.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/connector.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/connector_template.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/email.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/event.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_generic.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_report.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_generic.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_report.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/job.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/metering.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/quota.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_attribute.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_attribute_namespace.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_benchmark.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_offer.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_mapping.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/acl.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/cloud_entry_point.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common_operation.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_github.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_oidc.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_slipstream.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_ssh_public_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/description.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_internal.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_params_exec.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_params_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_params_template_exec.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_direct.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/common_test.cljc
  dummy-connector/config/src/com/sixsq/slipstream/connector/dummy_template.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1481 use admin identity to load creds in case of report external object
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_report_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_test.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1484 fix parameter descriptions
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_template_generic.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1486 fix: allow to create generic external object with href to template
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_generic_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_report_lifecycle_test.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1488 ignore special slipstream header on traefik
  cimi-deployment/docker-compose.yml
Labels: S40 Ready to validate

#1494 Issue six sq/nuvla box/#297 auto registration process
  cimi-test-jar/src/com/sixsq/slipstream/ssclj/resources/connector_test_utils.clj
  cimi-test-jar/src/com/sixsq/slipstream/ssclj/resources/credential_cloud_lifecycle_test_utils.clj
  dummy-connector/java/jar/src/test/java/com/sixsq/slipstream/connector/dummy/DummyCloudCredDefTest.java
  dummy-connector/java/jar/src/test/java/com/sixsq/slipstream/connector/dummy/DummyCloudCredentialsTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/CloudCredentialsTestBase.java
  jar-connector/src/test/java/com/sixsq/slipstream/util/CloudCredDefTestBase.java
Labels: S40 Ready to validate

#1496 allow default ordering for events to be overridden
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/event.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/event/test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/event_test.clj
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement
