Repository slipstream/SlipStreamServer, pull requests merged in 2018-09, with the labels that each got.

#1652 Fix splitting of user-id for cases where it contains slashes
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils_test.clj
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate, T5 Bug

#1654 Add billable attribute to the virtual-machine resource
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/virtual_machine_lifecycle_test.clj
Labels: S40 Ready to validate

#1656 Task/cimi deployment prototype 2
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_parameter.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_template.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/module.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment_parameter.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_parameter_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_template_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/deployment_parameter_test.cljc
Labels: S40 Ready to validate

#1660 add priority support to job resource
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_parameter.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/job.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_parameter_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/job_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/job_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1661 add disabledMonitoring attribute to cloud connectors
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud.cljc
  dummy-connector/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_dummy.cljc
  dummy-connector/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_dummy.cljc
  dummy-connector/config/test/com/sixsq/slipstream/connector/dummy_lifecycle_test.clj
  dummy-connector/config/test/com/sixsq/slipstream/connector/dummy_template_lifecycle_test.clj
  dummy-connector/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_dummy_test.cljc
  dummy-connector/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_dummy_test.cljc
Labels: P23 IFB, S40 Ready to validate, T2 Task

#1662 job with started time and total execution time
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/job.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/job_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/job_test.cljc
Labels: S40 Ready to validate

#1663 api key bug fix
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_api_key.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/credential_api_key_lifecycle_test.clj
Labels: S40 Ready to validate
