Repository slipstream/SlipStreamServer, pull requests merged in 2018-03, with the labels that each got.

#1412 finish containerization and tests with default es container
  README.md
  cimi-resources-rpm/pom.xml
  cimi-rpm/pom.xml
  ring-container-rpm/pom.xml
  ring-container/src/sixsq/slipstream/server/ring_container.clj
  ring-container/test/sixsq/slipstream/server/ring_container_test.clj
Labels: S40 Ready to validate

#1418 add all user roles into the request for api key/secret generation when provisioning VMs
  jar-connector/src/main/java/com/sixsq/slipstream/connector/CliConnectorBase.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/CliConnectorBaseTest.java
Labels: P66 EU-SEC, S40 Ready to validate

#1419 make container builds optional
  cimi-resources-rpm/pom.xml
  cimi-rpm/pom.xml
  ring-container-rpm/pom.xml
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1420 fix use of absolute ns
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1423 Docker docs
  README.md
Labels: S40 Ready to validate

#1424 automatically add user exec params when new external user is created
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1426 remove deprecated function
  cimi-test-jar/src/com/sixsq/slipstream/ssclj/resources/lifecycle_test_utils.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1429 Issue #1409 cimi external objects should have a content type attribute
  cimi-resources/project.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_report_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_test.cljc
Labels: S40 Ready to validate

#1430 ignore flaky tests
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1428 user template for standard self registration
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/callback_user_email_validation.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/user/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/user_self_registration.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/user_template_self_registration.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/user/utils_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_auto.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_direct.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_auto.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_direct.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_auto_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1431 Added deployment limits
  jar-service/src/main/java/com/sixsq/slipstream/run/Quota.java
  jar-service/src/main/java/com/sixsq/slipstream/run/RunNodeResource.java
Labels: S40 Ready to validate

#1434 remove auto template
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_auto.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_auto.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_direct.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_auto.clj
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
  cimi/test/com/sixsq/slipstream/auth/test_helper.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_lifecycle_test.clj
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/User.java
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1435 do not allow NEW users to login
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
  cimi/test/com/sixsq/slipstream/auth/test_helper.clj
  cimi/test/com/sixsq/slipstream/auth/utils/db_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1443 allow to provide bucket name for storing reports in object store
  cimi-resources-rpm/pom.xml
  cimi-resources-rpm/src/object-store-conf.edn.tmpl
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_report_lifecycle_test.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1446 change resource attribute to targetResource attribute
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/callback_email_validation.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/callback_user_email_validation.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/email/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/callback.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/user/utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/callback_example_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/callback_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/callback_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1439 reduce logging noise; increase levels for errors
  cimi-rpm/src/main/resources/log4j.properties
  cimi/src/com/sixsq/slipstream/ssclj/middleware/logger.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1445 webui fusion in static-content artifact
  rpm/pom.xml
  static-content/pom.xml
  static-content/src/main/assembly/static-content.xml
Labels: S40 Ready to validate

#1448 fix inter container dependencies
  README.md
  cimi-deployment/README.md
  cimi-deployment/components/traefik/.gitignore
  cimi-deployment/components/traefik/cert/do-not-remove
  cimi-deployment/components/traefik/cert/server.crt
  cimi-deployment/components/traefik/traefik-lets-encrypt.toml
  cimi-deployment/components/traefik/traefik-self-signed.toml
  cimi-deployment/docker-compose.yml
  cimi-rpm/pom.xml
Labels: S40 Ready to validate

#1449 fix binaries copy for static-content
  static-content/pom.xml
Labels: S40 Ready to validate

#1450 do not load credentials for super
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/User.java
Labels: S40 Ready to validate

#1452 add description for credential template for cloud connector
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential_template_cloud.clj
Labels: S40 Ready to validate

#1458 External object filename
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_template.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_template_report.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_report.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_report.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_alpha_example.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_template_alpha_example.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_template_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_report_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1465 new traefik version needs http challenge for LE
  cimi-deployment/components/traefik/traefik-lets-encrypt.toml
Labels: S40 Ready to validate

#1463 add postfix to docker image
  cimi-rpm/pom.xml
Labels: S40 Ready to validate

#1453 build arm image
  cimi-rpm/pom.xml
  cimi-rpm/src/assembly/container-bundle.xml
Labels: S40 Ready to validate

#1470 when deleting api key/secret use getRuntimeParameterValueIgnoreAbort()
  jar-connector/src/main/java/com/sixsq/slipstream/connector/CliConnectorBase.java
Labels: P66 EU-SEC, S40 Ready to validate

#1455 dynamically refresh service configuration on Configuration singleton from backend
  cimi-tools/src/com/sixsq/slipstream/tools/cli/utils.clj
  db-serializers/pom.xml
  db-serializers/project.clj
  db-serializers/src/com/sixsq/slipstream/db/serializers/service_config.clj
  db-serializers/src/com/sixsq/slipstream/db/serializers/service_config_impl.clj
  db-serializers/src/com/sixsq/slipstream/db/serializers/service_config_util.clj
  db-serializers/src/com/sixsq/slipstream/db/serializers/utils.clj
  db-serializers/test/com/sixsq/slipstream/db/serializers/service_config_impl_test.clj
  db-serializers/test/com/sixsq/slipstream/db/serializers/service_config_test.clj
  db-serializers/test/com/sixsq/slipstream/db/serializers/utils_test.clj
  jar-connector/src/test/java/com/sixsq/slipstream/configuration/ConfigurationTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/CliConnectorBaseTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/CloudCredentialsTestBase.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/ConnectorFactoryTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/ConnectorTestBase.java
  jar-connector/src/test/java/com/sixsq/slipstream/run/RunFactoryTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/run/RunTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/run/RuntimeParameterTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/util/CloudCredDefTestBase.java
  jar-connector/src/test/java/com/sixsq/slipstream/util/CommonTestUtil.java
  jar-persistence/pom.xml
  jar-persistence/src/main/java/com/sixsq/slipstream/configuration/Configuration.java
  jar-persistence/src/main/java/com/sixsq/slipstream/connector/ConnectorFactory.java
  jar-persistence/src/main/java/com/sixsq/slipstream/es/CljElasticsearchHelper.java
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/RuntimeParameter.java
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/ServiceConfiguration.java
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/ServiceConfigurationParameter.java
  jar-persistence/src/test/java/com/sixsq/slipstream/persistence/RunTest.java
  jar-persistence/src/test/java/com/sixsq/slipstream/util/UserTestUtil.java
  jar-service/src/main/java/com/sixsq/slipstream/application/RootApplication.java
  jar-service/src/main/java/com/sixsq/slipstream/resource/configuration/ServiceConfigurationFormProcessor.java
  jar-service/src/main/java/com/sixsq/slipstream/resource/configuration/ServiceConfigurationResource.java
  jar-service/src/test/java/com/sixsq/slipstream/configuration/ServiceConfigurationTest.java
  jar-service/src/test/java/com/sixsq/slipstream/initialstartup/UsersTest.java
  jar-service/src/test/java/com/sixsq/slipstream/module/ImageFormProcesorTest.java
  jar-service/src/test/java/com/sixsq/slipstream/module/ModuleResourceCopyToTest.java
  jar-service/src/test/java/com/sixsq/slipstream/user/UserResourceTest.java
  jar-service/src/test/java/com/sixsq/slipstream/util/ResourceTestBase.java
Labels: S40 Ready to validate

#1472 fix-user-self-registration-callback-url
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/user_self_registration.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
Labels: S40 Ready to validate
