Repository slipstream/SlipStreamServer, pull requests merged in 2018-10, with the labels that each got.

#1668 Cimi deployment fusion
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_template.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment/test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_template_lifecycle_test.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/std_crud.clj
Labels: S40 Ready to validate

#1675 metadata resource
  cimi/src/com/sixsq/slipstream/ssclj/resources/resource_metadata.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_action.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_attribute.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_capability.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_enumeration.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_item.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_range.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_single_value.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_unit.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/resource_metadata_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_action_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_attribute_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_capability_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_enumeration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_item_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_range_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_single_value_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_unit_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/util/es_mapping_test.cljc
  db-binding/src/com/sixsq/slipstream/db/es/common/es_mapping.cljc
Labels: P66 EU-SEC, S40 Ready to validate, T3 Enhancement

#1677 add metadata to specs
  cimi/project.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/acl.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common_namespaces.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_attribute.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/util/spec.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/common/utils_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/common_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_attribute_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_github_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_mitreid_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_oidc_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/util/es_mapping_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/util/spec_test.cljc
Labels: P66 EU-SEC, S40 Ready to validate, T3 Enhancement

#1678 add common parent and resourceMetadata attributes
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_attribute.cljc
Labels: P66 EU-SEC, S40 Ready to validate, T3 Enhancement

#1679 add attribute metadata
  cimi/src/com/sixsq/slipstream/ssclj/resources/credential.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/acl.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_ssh_key_pair.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_ssh_public_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_item.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_internal.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_mitreid_token.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_self_registration.cljc
  cimi/src/com/sixsq/slipstream/ssclj/util/spec.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/resource_metadata_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_item_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/resource_metadata_value_scope_test.cljc
Labels: P66 EU-SEC, S40 Ready to validate, T3 Enhancement

#1680 remove common parent attribute for now
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/common.cljc
Labels: S40 Ready to validate, T5 Bug

#1684 update email schema
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_email_validation.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/email.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/email_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/email_test.cljc
Labels: P66 EU-SEC, S40 Ready to validate, T5 Bug

#1688 switch to an atom for resource metadata storage
  cimi/src/com/sixsq/slipstream/ssclj/resources/resource_metadata.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/email.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/resource_metadata_lifecycle_test.clj
Labels: P66 EU-SEC, S40 Ready to validate, T2 Task

#1686 fix action authz
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_generic_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_lifecycle_test_utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_report_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_test.clj
Labels: P66 EU-SEC, S40 Ready to validate, T5 Bug
