Repository slipstream/SlipStreamServer, pull requests merged in 2018-02, with the labels that each got.

#1395 use User.roles for holding authz roles from the authn header
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/test/com/sixsq/slipstream/auth/utils/db_test.clj
  jar-persistence/src/main/java/com/sixsq/slipstream/credentials/CloudCredential.java
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/User.java
  jar-persistence/src/main/java/com/sixsq/slipstream/util/SscljProxy.java
  jar-persistence/src/test/java/com/sixsq/slipstream/persistence/UserTest.java
  jar-service/src/main/java/com/sixsq/slipstream/authn/CookieAuthenticator.java
  jar-service/src/main/java/com/sixsq/slipstream/user/UserParameterizedResource.java
  jar-service/src/main/java/com/sixsq/slipstream/user/UserResource.java
Labels: P66 EU-SEC, S40 Ready to validate

#1385 additional bindings
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_attribute_namespace.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/service_attribute_namespace_lifecycle_test.clj
  db-binding/pom.xml
  db-binding/project.clj
  db-binding/src/com/sixsq/slipstream/db/atom/binding.clj
  db-binding/src/com/sixsq/slipstream/db/binding.clj
  db-binding/src/com/sixsq/slipstream/db/es/acl.clj
  db-binding/src/com/sixsq/slipstream/db/es/binding.clj
  db-binding/src/com/sixsq/slipstream/db/es/common/pagination.clj
  db-binding/src/com/sixsq/slipstream/db/es/pagination.clj
  db-binding/src/com/sixsq/slipstream/db/es_rest/binding.clj
  db-binding/src/com/sixsq/slipstream/db/es_rest/order.clj
  db-binding/src/com/sixsq/slipstream/db/es_rest/pagination.clj
  db-binding/src/com/sixsq/slipstream/db/es_rest/select.clj
  db-binding/src/com/sixsq/slipstream/db/utils/acl.clj
  db-binding/src/com/sixsq/slipstream/db/utils/common.clj
  db-binding/src/com/sixsq/slipstream/db/utils/time_utils.clj
  db-binding/test/com/sixsq/slipstream/db/atom/binding_test.clj
  db-binding/test/com/sixsq/slipstream/db/binding_lifecycle.clj
  db-binding/test/com/sixsq/slipstream/db/es/binding_test.clj
  db-binding/test/com/sixsq/slipstream/db/es/common/pagination_test.clj
  db-binding/test/com/sixsq/slipstream/db/es/es_node.clj
  db-binding/test/com/sixsq/slipstream/db/es/filter_test.clj
  db-binding/test/com/sixsq/slipstream/db/es_rest/binding_test.clj
  db-binding/test/com/sixsq/slipstream/db/utils/common_test.clj
  db-testing/project.clj
  db-testing/src/com/sixsq/slipstream/dbtest/es/spandex_utils.clj
  db-testing/src/com/sixsq/slipstream/dbtest/es/utils.clj
  utils/src/com/sixsq/slipstream/util/response.clj
  utils/test/com/sixsq/slipstream/util/response_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1393 use api key/secret for the deployments instead of machine cookie
  dummy-connector/java/jar/pom.xml
  jar-connector/pom.xml
  jar-connector/src/main/java/com/sixsq/slipstream/connector/CliConnectorBase.java
  jar-connector/src/main/java/com/sixsq/slipstream/connector/ConnectorBase.java
  jar-connector/src/main/java/com/sixsq/slipstream/cookie/CookieUtils.java
  jar-connector/src/main/java/com/sixsq/slipstream/factory/RunFactory.java
  jar-connector/src/test/java/com/sixsq/slipstream/connector/CliConnectorBaseTest.java
  jar-connector/src/test/java/com/sixsq/slipstream/run/RunTestBase.java
  jar-persistence/pom.xml
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/RuntimeParameter.java
  jar-service/pom.xml
Labels: P66 EU-SEC, S40 Ready to validate

#1405 allow user to view connector instance configuration
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/connector.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/connector_lifecycle_test.clj
Labels: P66 EU-SEC, S40 Ready to validate

#1406 log thread identities for garbage collection
  jar-connector/src/main/java/com/sixsq/slipstream/util/Terminator.java
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1399 Reports migration script
  rpm/src/main/migrations/021_migrate_reports_to_cimi.py
Labels: S40 Ready to validate

#1408 removed reports from java
  cimi/resources/com/sixsq/slipstream/ssclj/resources/configuration-slipstream-desc.edn
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_slipstream.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_slipstream.cljc
  db-serializers/src/com/sixsq/slipstream/db/serializers/service_config_impl.clj
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/ServiceConfiguration.java
  jar-service/src/main/java/com/sixsq/slipstream/application/RootApplication.java
  jar-service/src/main/java/com/sixsq/slipstream/authz/ReportsAuthorizer.java
  jar-service/src/main/java/com/sixsq/slipstream/filter/ReportDecorator.java
  jar-service/src/main/java/com/sixsq/slipstream/resource/FileProperties.java
  jar-service/src/main/java/com/sixsq/slipstream/resource/FilePropertiesList.java
  jar-service/src/main/java/com/sixsq/slipstream/resource/ReportRouter.java
  jar-service/src/main/java/com/sixsq/slipstream/resource/ResultsDirectory.java
  jar-service/src/main/java/com/sixsq/slipstream/run/RunListResource.java
  jar-service/src/test/java/com/sixsq/slipstream/resource/FilePropertiesListTest.java
  jar-service/src/test/java/com/sixsq/slipstream/resource/FilePropertiesTest.java
  jar-service/src/test/java/com/sixsq/slipstream/resource/ResultsDirectoryTest.java
  jar-service/src/test/java/com/sixsq/slipstream/resource/TestData.java
Labels: S40 Ready to validate

#1415 report-migration-script-fix
  rpm/src/main/migrations/021_migrate_reports_to_cimi.py
Labels: S40 Ready to validate
