Repository slipstream/SlipStreamServer, pull requests merged in 2018-07, with the labels that each got.

#1590 Issue #1582 update authentication methods to use user identifier
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/utils.clj
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
  cimi/test/com/sixsq/slipstream/auth/test_helper.clj
  cimi/test/com/sixsq/slipstream/auth/utils/db_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate

#1592 disable ADMIN header
  cimi-deployment/docker-compose.yml
Labels: S40 Ready to validate

#1593 use common utilities for testing namespaces
  cimi-resources/project.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/connector_template_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/connector_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/event_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/evidence_record_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_generic_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_report_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_generic_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_report_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/job_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/metering_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/quota_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_attribute_namespace_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_attribute_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_benchmark_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_offer_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/util.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_mapping_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_test.cljc
  cimi-test-jar/project.clj
  cimi-test-jar/src/com/sixsq/slipstream/ssclj/resources/spec/spec_test_utils.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1597 allow autocomplete in descriptions
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/description.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_self_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/description_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1596 Task/user creation redirect
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_github_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_self_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1601 add logging for errors when retrieving access token
  cimi/src/com/sixsq/slipstream/auth/oidc.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1602 Issue #1599 oidc session with mangled identifiers
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils_test.clj
Labels: S40 Ready to validate

#1606 allow for direct authentication with MITREid access token
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_session_mitreid_token.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_session_mitreid_token.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_mitreid_token.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_mitreid_token.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_mitreid_token.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_mitreid_token.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_oidc_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/configuration_template_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_mitreid_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_mitreid_token_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_mitreid_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_mitreid_token_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_mitreid_token_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1607 add full text search with simple query string
  db-binding/resources/com/sixsq/slipstream/db/filter/cimi-filter-grammar.txt
  db-binding/src/com/sixsq/slipstream/db/es/filter.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1610 prototype module resources
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/module.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/module/utils.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/module_application.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/module_component.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/module_image.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module_application.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module_component.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/module_image.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module/utils_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module_application_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module_component_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module_image_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_application_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_component_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_image_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_test.cljc
  rpm/src/main/migrations/022_migrate_module_to_cimi.py
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1608 add/use correct credentials for terminate
  jar-connector/src/main/java/com/sixsq/slipstream/connector/CliConnectorBase.java
  jar-connector/src/main/java/com/sixsq/slipstream/connector/ConnectorBase.java
  jar-connector/src/main/java/com/sixsq/slipstream/factory/RunFactory.java
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/RuntimeParameter.java
  jar-persistence/src/main/java/com/sixsq/slipstream/persistence/User.java
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1603 Task/prepare user identifier migration
  cimi-migration/README.md
  cimi-migration/pom.xml
  cimi-migration/project.clj
  cimi-migration/resources/log4j.properties
  cimi-migration/src/assembly/src.xml
  cimi-migration/src/com/sixsq/slipstream/tools/cli/users_migration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_identifier.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_identifier_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user/user_identifier_utils_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1613 fix also for session creation
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_mitreid.clj
Labels: P45 MF2C, T5 Bug

#1614 Added "managers" to cloud credentials.
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud.cljc
Labels: S40 Ready to validate

#1615 fix access rights for module
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/module.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1616 expand ui hints; use common definitions
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/ui_hints.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/ui_hints.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1618 return redirect on invalid parameters if redirectURI is present
  cimi/src/com/sixsq/slipstream/ssclj/resources/session.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_internal_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1626 verify user registration lifecycles
  cimi/src/com/sixsq/slipstream/ssclj/resources/user.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_direct.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_self_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_direct.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
Labels: S40 Ready to validate, T5 Bug

#1624 change quota limit type to natural
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/quota.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/quota_test.cljc
Labels: S40 Ready to validate

#1629 change pattern for sesson template identifiers
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_github_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_oidc_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_self_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_mitreid_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_oidc_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
Labels: P25 MOOC, S40 Ready to validate, T2 Task
