Repository slipstream/SlipStreamServer, pull requests merged in 2018-08, with the labels that each got.

#1612 deployment resource prototypes
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/deployment_template.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment_parameter.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/deployment_template.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_template_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/module_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/deployment_parameter_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/deployment_template_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/deployment_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1635 create bucky resource
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/storage_bucket.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/storage_bucket.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/storage_bucket_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/storage_bucket_lifecycle_test.clj
Labels: S40 Ready to validate

#1641 Issue #1666 configure metering to also snapshot records from bucky
  metering/src/sixsq/slipstream/metering/metering.clj
  metering/src/sixsq/slipstream/metering/service.clj
  metering/test/sixsq/slipstream/metering/metering_live_test.clj
  metering/test/sixsq/slipstream/metering/metering_test.clj
Labels: S40 Ready to validate, T2 Task

#1644 Assume storage bucket unit is always KiB
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/storage_bucket.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/storage_bucket_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/storage_bucket_lifecycle_test.clj
  metering/src/sixsq/slipstream/metering/metering.clj
  metering/test/sixsq/slipstream/metering/metering_live_test.clj
  metering/test/sixsq/slipstream/metering/metering_test.clj
Labels: S40 Ready to validate

#1647 redirect on schema error when requested
  cimi/src/com/sixsq/slipstream/ssclj/resources/session.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1648 Copy the service offer resource type at the top level metering resource
  metering/src/sixsq/slipstream/metering/metering.clj
  metering/test-resources/virtual-machines.json
  metering/test/sixsq/slipstream/metering/metering_live_test.clj
  metering/test/sixsq/slipstream/metering/metering_test.clj
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#1638 Issue #1636 add currency attribute to storage buckets and virtual machines
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/metering.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/storage_bucket.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/storage_bucket.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/virtual_machine.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/metering_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/storage_bucket_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/storage_bucket_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/virtual_machine_lifecycle_test.clj
Labels: S40 Ready to validate, T2 Task

#1649 Add missing env variable
  metering-rpm/src/scripts/metering
Labels: S40 Ready to validate, T5 Bug

#1650 implement cimi delete attribute on edit
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_lifecycle_test.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/std_crud.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/utils.clj
Labels: S40 Ready to validate

#1651 es use reindex instead of update for edit operation
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/deployment_lifecycle_test.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_application_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_component_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_image_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/module_test.cljc
  db-binding/src/com/sixsq/slipstream/db/es/utils.clj
Labels: S40 Ready to validate
