Repository slipstream/SlipStreamServer, pull requests merged in 2018-06, with the labels that each got.

#1545 remove reference to clojure.spec.gen
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_attribute_namespace.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1542 Cleanup references to cyclone authentication
  cimi-rpm/pom.xml
  cimi-rpm/src/assembly/container-bundle.xml
  cimi-rpm/src/main/resources/cyclone_pubkey.pem
  cimi-rpm/src/main/systemd/cimi.service
  cimi/src/com/sixsq/slipstream/auth/cyclone.clj
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/app/routes.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_cyclone.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_cyclone.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_cyclone.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/test-resources/cyclone_pubkey.pem
  cimi/test/com/sixsq/slipstream/auth/cyclone_test.clj
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_cyclone_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_oidc_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_template_cyclone_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_cyclone_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_github_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_internal_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_oidc_test.cljc
Labels: S40 Ready to validate

#1541 Issue #1532 create callback ressource for GitHub session creation
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc/utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_oidc_lifecycle_test.clj
Labels: S40 Ready to validate

#1549 Issue #1548 create user registration template for GitHub
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/github/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_template_github_registration.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_github_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_github_registration.clj
  cimi/test/com/sixsq/slipstream/auth/utils/db_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_template_github_registration_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1550 Update test on github registration
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1553 update specs to use file-based namespaces
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_internal.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_github.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_oidc.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_api_key.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_github.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_internal.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/session_template_oidc.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_github_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_internal_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_template_oidc_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/session_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1554 Issue #1551 harmonize external login
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
  cimi/test/com/sixsq/slipstream/auth/utils/db_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1555 Remove extra name attribute in user schema
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1560 check user creation with forms
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_direct_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1561 Tasklist/issue #1592/nuvlabox resources
  cimi-test-jar/src/com/sixsq/slipstream/ssclj/resources/lifecycle_test_utils.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
Labels: S40 Ready to validate

#1558 Issue #1556 change oidc configuration parameters
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_oidc.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_oidc_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_github_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_oidc_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1557 make the user templates into persistent resources
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_direct.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_github_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_oidc_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template_self_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_direct_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_self_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_template_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1564 Add client secret to the list of parameters for the tokenURL query
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/oidc.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_oidc.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/core.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_oidc_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_oidc_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
  token/clj/project.clj
  token/clj/src/com/sixsq/slipstream/auth/utils/certs.clj
  token/clj/src/com/sixsq/slipstream/auth/utils/sign.clj
  token/java/project.clj
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#1566 update external identity management
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/github.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_github.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user.cljc
  cimi/test/com/sixsq/slipstream/auth/external_test.clj
  cimi/test/com/sixsq/slipstream/auth/utils/db_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1568 remove duplicate slf4j jar from rpm package
  cimi-rpm/pom.xml
  cimi/project.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1574 job resource - add zookeeper path to properties
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job/utils.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/job_lifecycle_test.clj
Labels: S40 Ready to validate

#1576 consistently use function retrieve-by-id-as-admin
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/connector.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/quota.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_email_validation.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_user_email_validation.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/github/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_api_key.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_template.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_template.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1578 Task/remove base url for oidc configs
  cimi/src/com/sixsq/slipstream/auth/oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/configuration_template_session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_mitreid.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/session_oidc/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_mitreid.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/configuration_template_session_oidc.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_oidc_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/configuration_template_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_mitreid_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/session_oidc_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1581 add user identifier resource
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/email/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/user_identifier.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_identifier.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/spec_test_utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_identifier_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_identifier_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1583 don't allow edits on evidenceRecords
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/evidence_record.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/evidence_record_lifecycle_test.clj
Labels: S40 Ready to validate

#1584 use aliased ns keywords
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/event.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/evidence_record.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_generic.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_report.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_template_generic.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/external_object_template_report.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/job.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/metering.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/quota.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_attribute.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_attribute_namespace.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_benchmark.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/service_offer.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/connector_template.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/event.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/evidence_record.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_generic.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_report.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_generic.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_report.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/job.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/metering.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/quota.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_attribute.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_attribute_namespace.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_benchmark.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/service_offer.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_mapping.cljc
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/virtual_machine.clj
  cimi-resources/src/com/sixsq/slipstream/ssclj/resources/virtual_machine_mapping.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/connector_template_alpha_example.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/external_object_template_alpha_example.clj
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/event_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_generic_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_report_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_generic_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_template_report_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/external_object_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/job_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/metering_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/quota_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_attribute_namespace_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_attribute_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_benchmark_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/service_offer_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_mapping_test.cljc
  cimi-resources/test/com/sixsq/slipstream/ssclj/resources/spec/virtual_machine_test.cljc
  cimi/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud.cljc
  dummy-connector/config/src/com/sixsq/slipstream/connector/dummy_template.clj
  dummy-connector/config/src/com/sixsq/slipstream/ssclj/resources/credential_cloud_dummy.clj
  dummy-connector/config/src/com/sixsq/slipstream/ssclj/resources/credential_template_cloud_dummy.clj
  dummy-connector/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_dummy.cljc
  dummy-connector/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_dummy.cljc
  dummy-connector/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_dummy_test.cljc
  dummy-connector/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_dummy_test.cljc
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#1585 force the user record to contain the correct method
  cimi/src/com/sixsq/slipstream/auth/external.clj
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/callback_create_user_oidc.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/spec_test_utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_identifier_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#1588 Fix method attribute when creating a user
  cimi/src/com/sixsq/slipstream/auth/utils/db.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/common/utils.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_github_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration.clj
  cimi/src/com/sixsq/slipstream/ssclj/resources/user_oidc_registration.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/spec_test_utils.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/spec/user_identifier_test.cljc
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_github_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_mitreid_registration_lifecycle_test.clj
  cimi/test/com/sixsq/slipstream/ssclj/resources/user_oidc_registration_lifecycle_test.clj
Labels: S40 Ready to validate

#1589 fix 500 errors from uncaught exceptions
  cimi/src/com/sixsq/slipstream/ssclj/resources/session.clj
  db-binding/src/com/sixsq/slipstream/db/es/binding.clj
Labels: P45 MF2C, S40 Ready to validate, T5 Bug
